

name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: [ubuntu-latest]


    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Build with Gradle
      uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
      with:
        arguments: build

   - name: Build

        run: |
          mvn clean install
          
  - name: Login to DockerHub

    uses: docker/login-action@v2.1.0

    with:

      registry: registry-url.io

      username: ${{ secrets.DOCKER_USERNAME }}

      password: ${{ secrets.DOCKER_PASSWORD }}

  - name: Build the Docker image

    run: |

      docker build -t registry-url.io/chandu8121/new .
      docker push  docker build -t registry-url.io/chandu8121/new
     

